name: Check Markdown links

# Run action on any push event in the repo
on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    # checkout to latest commit
    - uses: actions/checkout@master
    # run markdown linter
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
